services:
  - type: web
    name: tokyo-coffee-chats-api
    env: node
    plan: free
    buildCommand: |
      npm install
      npm run db:generate
      npm run db:reset
      npm run db:deploy
      npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: tokyo-postgres
          property: connectionString
    healthCheckPath: /api/coffee-chats
    autoDeploy: true

databases:
  - name: tokyo-postgres
    databaseName: tokyo_coffee_chats
    user: tokyo_user
    plan: free
    ipAllowList: []
    version: "15"
